listings:
    resource: Nuada\ApiBundle\Controller\ListingsController
    prefix: /api
    type:  rest

agencies:
    resource: Nuada\ApiBundle\Controller\AgenciesController
    prefix: /api
    type:  rest

locations:
    resource: Nuada\ApiBundle\Controller\LocationsController
    prefix: /api
    type:  rest

photos:
    resource: Nuada\ApiBundle\Controller\PhotosController
    prefix: /api
    type:  rest

agents:
    resource: Nuada\ApiBundle\Controller\AgentsController
    prefix: /api
    type:  rest

summary:
    resource: Nuada\ApiBundle\Controller\SummaryController
    prefix: /api
    type:  rest

neighbourhoodmetrics:
    resource: Nuada\ApiBundle\Controller\NeighbourhoodMetricsController
    prefix: /api
    type:  rest

listingdetails:
    resource: Nuada\ApiBundle\Controller\ListingDetailsController
    prefix: /api
    type:  rest

neighbourhoods:
    resource: Nuada\ApiBundle\Controller\NeighbourhoodsController
    prefix: /api
    type:  rest

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
