listings:
    resource: Nuada\ApiBundle\Controller\ListingsController
    prefix: /api
    type:  rest

agencie:
    resource: Nuada\ApiBundle\Controller\AgenciesController
    prefix: /api
    type:  rest

