listings:
    resource: Nuada\ApiBundle\Controller\ListingsController
    prefix: /api
    type:  rest

addlistings:
    resource: Nuada\ApiBundle\Controller\AddlistingsController
    prefix: /api
    type:  rest

agencies:
    resource: Nuada\ApiBundle\Controller\AgenciesController
    prefix: /api
    type:  rest

locations:
    resource: Nuada\ApiBundle\Controller\LocationsController
    prefix: /api
    type:  rest

photos:
    resource: Nuada\ApiBundle\Controller\PhotosController
    prefix: /api
    type:  rest

agents:
    resource: Nuada\ApiBundle\Controller\AgentsController
    prefix: /api
    type:  rest

summary:
    resource: Nuada\ApiBundle\Controller\SummaryController
    prefix: /api
    type:  rest

neighbourhoodmetrics:
    resource: Nuada\ApiBundle\Controller\NeighbourhoodMetricsController
    prefix: /api
    type:  rest

listingdetails:
    resource: Nuada\ApiBundle\Controller\ListingDetailsController
    prefix: /api
    type:  rest

neighbourhoods:
    resource: Nuada\ApiBundle\Controller\NeighbourhoodsController
    prefix: /api
    type:  rest

neighbourhoodenquiries:
    resource: Nuada\ApiBundle\Controller\NeighbourhoodEnquiriesController
    prefix: /api
    type:  rest

experts:
    resource: Nuada\ApiBundle\Controller\ExpertsController
    prefix: /api
    type:  rest

favorites:
    resource: Nuada\ApiBundle\Controller\FavoritesController
    prefix: /api
    type:  rest

logout:
    resource: Nuada\ApiBundle\Controller\LogoutController
    prefix: /api
    type:  rest

blogs:
    resource: Nuada\ApiBundle\Controller\BlogsController
    prefix: /api
    type:  rest

files:
    resource: Nuada\ApiBundle\Controller\FilesController
    prefix: /api
    type:  rest

reviews:
    resource: Nuada\ApiBundle\Controller\ReviewsController
    prefix: /api
    type:  rest

useragencies:
    resource: Nuada\ApiBundle\Controller\UserAgenciesController
    prefix: /api
    type:  rest

updateduser:
    resource: Nuada\UserBundle\Controller\UpdateduserController
    prefix: /api
    type:  rest

advertisements:
    resource: Nuada\ApiBundle\Controller\AdvertisementsController
    prefix: /api
    type:  rest

users:
    resource: Nuada\UserBundle\Controller\UsersController
    prefix: /api
    type:  rest

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
