listings:
    resource: Nuada\ApiBundle\Controller\ListingsController
    prefix: /api
    type:  rest

agencies:
    resource: Nuada\ApiBundle\Controller\AgenciesController
    prefix: /api
    type:  rest

listing_details:
    resource: Nuada\ApiBundle\Controller\ListingdetailsController
    prefix: /api
    type:  rest

locations:
    resource: Nuada\ApiBundle\Controller\LocationsController
    prefix: /api
    type:  rest

