security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/auth/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /auth/login
                check_path: /auth/login_check

            logout:
                path:   /auth/logout
                target: /api/logout 
            anonymous:    true

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/auth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
