<?php

namespace Nuada\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UpdatedUserRepository
 *
 * This class was generated by the Doctrine ORM.
 */
class UpdatedUserRepository extends EntityRepository
{
	/**
     * Retrieve
     *
     * @param integer $id - Updated User Id
     *
     * @return UpdatedUser
     */
    public function retrieve($id)
    {
        return $this->find($id);
    }
}
