services:
      nuada_api.listing_manager:
        class: Nuada\ApiBundle\Manager\ListingManager
        arguments:
        - @doctrine
        - @security.context
        - @validator
        - @nuada_api.agency_manager
        - @nuada_api.photo_manager
        - @nuada_api.agent_manager

      nuada_api.agency_manager:
        class: Nuada\ApiBundle\Manager\AgencyManager
        arguments:
        - @doctrine
        - @security.context
        - @validator
        - @nuada_api.photo_manager
        - @nuada_api.agent_manager
        - @doctrine.dbal.default_connection

      nuada_api.location_manager:
        class: Nuada\ApiBundle\Manager\LocationManager
        arguments:
        - @doctrine
        - @security.context
        - @validator
        - @doctrine.dbal.default_connection
        - @service_container

      nuada_api.photo_manager:
        class: Nuada\ApiBundle\Manager\PhotoManager
        arguments:
        - @doctrine
        - @security.context
        - @validator

      nuada_api.agent_manager:
        class: Nuada\ApiBundle\Manager\AgentManager
        arguments:
        - @doctrine
        - @security.context
        - @validator

      nuada_api.summary_manager:
        class: Nuada\ApiBundle\Manager\SummaryManager
        arguments:
        - @doctrine
        - @security.context
        - @validator

      nuada_api.neighbourhood_metric_manager:
        class: Nuada\ApiBundle\Manager\NeighbourhoodMetricManager
        arguments:
        - @doctrine
        - @security.context
        - @validator

      nuada_api.listing_detail_manager:
        class: Nuada\ApiBundle\Manager\ListingDetailManager
        arguments:
        - @doctrine
        - @security.context
        - @validator

      nuada_api.neighbourhood_manager:
        class: Nuada\ApiBundle\Manager\NeighbourhoodManager
        arguments:
        - @doctrine
        - @security.context
        - @validator
        - @nuada_api.photo_manager
        - @nuada_api.agency_manager
        - @doctrine.dbal.default_connection

      nuada_api.neighbourhood_enquiry_manager:
        class: Nuada\ApiBundle\Manager\NeighbourhoodEnquiryManager
        arguments:
        - @doctrine
        - @security.context
        - @validator
        - @nuada_api.neighbourhood_manager

      nuada_api.expert_manager:
        class: Nuada\ApiBundle\Manager\ExpertManager
        arguments:
        - @doctrine
        - @security.context
        - @validator

      nuada_api.favorite_manager:
        class: Nuada\ApiBundle\Manager\FavoriteManager
        arguments:
        - @doctrine
        - @security.context
        - @validator
        - @nuada_api.listing_manager

      nuada_api.agency_nbh_manager:
        class: Nuada\ApiBundle\Manager\AgencyNeighbourhoodManager
        arguments:
        - @doctrine
        - @security.context
        - @validator
        - @nuada_api.agency_manager

      nuada_api.blog_manager:
          class: Nuada\ApiBundle\Manager\BlogManager
          arguments:
          - @doctrine
          - @security.context
          - @validator
          - @doctrine.dbal.default_connection

      nuada_api.review_manager:
          class: Nuada\ApiBundle\Manager\ReviewManager
          arguments:
          - @doctrine
          - @security.context
          - @validator
          - @nuada_api.agency_manager
          - @nuada_api.agent_manager

      nuada_api.file_manager:
          class: Nuada\ApiBundle\Manager\FileManager
          arguments:
          - @doctrine
          - @security.context
          - @validator
          - @service_container

      nuada_api.user_agency_manager:
        class: Nuada\ApiBundle\Manager\UserAgencyManager
        arguments:
        - @doctrine
        - @security.context
        - @validator
        - @nuada_api.agency_manager

      nuada_api.advertisement_manager:
        class: Nuada\ApiBundle\Manager\AdvertisementManager
        arguments:
        - @doctrine
        - @security.context
        - @validator
        