services:
      nuada_api.listing_manager:
        class: Nuada\ApiBundle\Manager\ListingManager
        arguments:
        - @doctrine
        - @security.context
        - @validator

      nuada_api.agency_manager:
        class: Nuada\ApiBundle\Manager\AgencyManager
        arguments:
        - @doctrine
        - @security.context
        - @validator