<?php

namespace Nuada\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgencyNeighbourhoodRepository
 *
 * This class was generated by the Doctrine ORM
 */
class AgencyNeighbourhoodRepository extends EntityRepository
{
    /**
     * Retrieve All
     *
     * @param integer $id               - id
     * @param integer $agencyId         - Agency Id
     * @param integer $neighbourhoodId  - Neighbourhood Id
     * @param boolean $withDeleted      - With deleted mapping
     *
     * @return array
     */
    public function retrieveAll(
        $id=null,
        $agencyId=null,
        $neighbourhoodId=null,
        $withDeleted=false)
    {
        $qb = $this->createQueryBuilder('e');

        if (!is_null($id)) {
            $qb = $qb->andWhere('e.id = :id')
                ->setParameter('id', $id);
        }

        if (!$withDeleted) {
            $qb = $qb->andWhere('e.deleted = false');
        }

        if (!is_null($agencyId)) {
            $qb = $qb->andWhere('e.agencyId = :agencyId')
                ->setParameter('agencyId', $agencyId);
        }

        if (!is_null($neighbourhoodId)) {
            $qb = $qb->andWhere('e.neighbourhoodId = :neighbourhoodId')
                ->setParameter('neighbourhoodId', $neighbourhoodId);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
