<?php

namespace Nuada\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactAgencyRepository
 *
 * This class was generated by the Doctrine ORM. 
 */
class ContactAgencyRepository extends EntityRepository
{
    public function retrieveAll(
            $id=null,
            $limit=null,
            $offset=null,
            $withDeleted=null,
            $name=null,
            $phone=null,
            $email=null,
            $customerType=null,
            $agencyId=null)
    {
        if (!is_null($id)) {
            return $this->find($id);
        }

        $qb = $this->createQueryBuilder('e');

        if (!$withDeleted) {
            $qb = $qb->andWhere('e.deleted = false');
        }
        
        if (!is_null($name)) {
            $qb = $qb->andWhere('e.name = :name')
                     ->setParameter('name', $name);
        }

        if (!is_null($phone)) {
            $qb = $qb->andWhere('e.phone = :phone')
                     ->setParameter('phone', $phone);
        }

        if (!is_null($email)) {
            $qb = $qb->andWhere('e.email = :email')
                     ->setParameter('email', $email);
        }

        if (!is_null($customerType)) {
            $qb = $qb->andWhere('e.customerType = :customerType')
                     ->setParameter('customerType', $rcustomerTypeank);
        }

        if (!is_null($agencyId)) {
            $qb = $qb->andWhere('e.agencyId = :agencyId')
                     ->setParameter('agencyId', $agencyId);
        }

        if ($sortOn) {
            $order = $this->getSortCriteria($sortOn, $reverse);
            
            $qb->orderBy('e.'.$order['column'], $order['direction']);
        }
        
        if ($offset) {
            $qb->setMaxResults($limit);
            $qb->setFirstResult($offset);
        }

        if ($limit && !$offset) {
            $qb->setMaxResults($limit);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
