<?php

namespace Nuada\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListingDetailRepository
 *
 * This class was generated by the Doctrine ORM
 */
class ListingDetailRepository extends EntityRepository
{
    /**
     * Retrieve All
     *
     * @param integer $id          - id
     * @param integer $type        - Listing type
     * @param boolean $withDeleted - With deleted listing
     *
     * @return array
     */
    public function retrieveAll(
        $id=null,
        $type=null,
        $withDeleted=false)
    {
        $qb = $this->createQueryBuilder('e');

        if (!is_null($id)) {
            $qb = $qb->andWhere('e.id = :id')
                ->setParameter('id', $id);
        }

        if (!$withDeleted) {
            $qb = $qb->andWhere('e.deleted = false');
        }

        if (!is_null($type)) {
            $qb = $qb->andWhere('e.listingType = :listingType')
                ->setParameter('listingType', $type);
        }


        $query = $qb->getQuery();

        return $query->getResult();
    }
}

