<?php

namespace Nuada\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NeighbourhoodRepository
 *
 * This class was generated by the Doctrine ORM
 */
class NeighbourhoodRepository extends EntityRepository
{
    /**
     * Retrieve All
     *
     * @param integer $id           - id
     * @param integer $name         - Neighbourhood name
     * @param boolean $withDeleted  - With deleted mapping
     * @param integer $offset       - Offset
     * @param integer $limit        - Limit
     *
     * @return array
     */
    public function retrieveAll(
        $id=null,
        $name=null,
        $withDeleted=false,
        $offset=null,
        $limit=null)
    {
        $qb = $this->createQueryBuilder('e');

        if (!is_null($id)) {
            $qb = $qb->andWhere('e.id = :id')
                ->setParameter('id', $id);
        }

        if (!$withDeleted) {
            $qb = $qb->andWhere('e.deleted = false');
        }

        if (!is_null($name)) {
            $qb = $qb->andWhere('e.name = :name')
                ->setParameter('name', $name);
        }

        if ($offset) {
            $qb->setMaxResults($limit);
            $qb->setFirstResult($offset);
        }

        if ($limit && !$offset) {
            $qb->setMaxResults($limit);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }

    /**
     * Retrieve All
     *
     * @param integer $id          - Listing Id
     * @param string  $name        - Name
     * @param boolean $withDeleted - With deleted neighbourhood
     *
     * @return array
     */
    public function fetchCount(
        $id = null,
        $name = null,
        $withDeleted = false)
    {
        $qb = $this->createQueryBuilder('e')
            ->select('count(e)');

        if (!is_null($id)) {
            $qb = $qb->andWhere('e.id = :id')
                ->setParameter('id', $id);
        }

        if (!$withDeleted) {
            $qb = $qb->andWhere('e.deleted = false');
        }

        if (!is_null($name)) {
            $qb = $qb->andWhere('e.name = :name')
                ->setParameter('name', $name);
        }

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();
    }

    /**
     * Retrieve All
     *
     * @param integer $count        - Count
     * @param boolean $withDeleted  - With deleted mapping
     * @param integer $offset       - Offset
     * @param integer $limit        - Limit
     *
     * @return array
     */
    public function retrieveTop(
        $count=null,
        $withDeleted=false)
    {
        $qb = $this->createQueryBuilder('e');

        if (!$withDeleted) {
            $qb = $qb->andWhere('e.deleted = false');
        }

        if ($count) {
            $qb->setMaxResults($count);
        }

        $qb = $qb->orderBy('e.score', 'DESC');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
